### ISSUE TITLE
Improve Postgres compatibility

### ISSUE THREAD

**Issue by sandord** [sandord/Respawn.Postgres#1]
- [ ] ~Figure out what versions of Postgres the queries are compatible with.~
- [x] Attempt to improve compatibility. The database structure hash query may be sensitive to Postgres updates, either breaking or missing new parts. Perhaps we can iterate the columns that are currently selected statically.
- [ ] Update docs accordingly
- [ ] ~Provide a mechanism that can select compatible queries for certain Postgres version ranges.~

**Comment by sandcastle** [comment]
@sandord - I'm getting the following error when trying to run against `v9.6`, this is because logical replication was not introduced until `v10`.

> column f.attidentity does not exist

## Analysis

I have completed an analysis of `9.6`, `10`, `11` and `12` (beta) against all tables and views used in the hash:

[respawn.xlsx](https://github.com/sandord/Respawn.Postgres/files/3614565/respawn.xlsx)

**Comment by sandcastle** [comment]
@sandord - How far back do you think the versioning support should go? Looking at the versioning of Postgres `9.4` is supported until `February 13, 2020`. In theory, this library should support all supported versions.

https://www.postgresql.org/support/versioning/

**Comment by sandcastle** [comment]
Options for selecting a specific version of postgres:

```sql
select version();
-- PostgreSQL 9.6.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.2.0) 8.2.0, 64-bit

SHOW server_version;
-- 9.6.12

SELECT current_setting('server_version_num');
-- 90612

select current_setting('server_version');
-- 9.6.12

-- major version
select (regexp_matches(current_setting('server_version'), '(\d+)\.(\d+)\.(\d+)'))[1];
-- 9

-- minor version
select (regexp_matches(current_setting('server_version'), '(\d+)\.(\d+)\.(\d+)'))[2];
-- 6
```

Using `current_setting('server_version')` with a regex looks like the easiest way to determine the major and minor versions.

**Comment by sandord** [comment]
Thanks for looking into this.

As stated above, I was thinking of iterating the available system columns dynamically. That would make it work for any version automatically.

I haven't much time in the near future. Perhaps you could do a PR if you'd like?

**Comment by sandcastle** [comment]
To do a Postgres only dynamic query you would need to create and drop a function that can return the MD5, so probably easier to pull the column names back to .Net and then construct the query from there:

```sql
select 
	t.table_name as view_name,
	c.column_name,
	t.table_type
from information_schema.tables t
left join information_schema.columns c 
	on t.table_schema = c.table_schema 
	and t.table_name = c.table_name
where (table_type = 'VIEW' and t.table_name = 'columns')
or t.table_type = 'BASE TABLE' and t.table_name in (
	'pg_class',
	'pg_type',
	'pg_attrdef',
	'pg_namespace',
	'pg_constraint'
)
;
```

When I get some time I will have a go at this solution.

**Comment by sandord** [comment]
Good thinking!

**Comment by sandcastle** [comment]
See #4 PR

**Comment by sandord** [comment]
Excellent! I will look at it as soon as possible.

**Comment by nurlybekovnt** [comment]
On postgres version 12 the column `consrc` no longer exists in table pg_constraint. [offdoc](https://www.postgresql.org/docs/12/catalog-pg-constraint.html)

**Comment by sandord** [comment]
> On postgres version 12 the column `consrc` no longer exists in table pg_constraint. [offdoc](https://www.postgresql.org/docs/12/catalog-pg-constraint.html)

@sandcastle's PR https://github.com/sandord/Respawn.Postgres/pull/4 should fix this (which I'm terribly late reviewing for... sorry!). Please hang on while I'm reviewing it.

**Comment by sandord** [comment]
> On postgres version 12 the column `consrc` no longer exists in table pg_constraint. [offdoc](https://www.postgresql.org/docs/12/catalog-pg-constraint.html)

This should be fixed in the latest NuGet package.
