### ISSUE TITLE
Npgsql exception: Column c.consrc does not exist

### ISSUE THREAD

**Issue by Kingmidas74** [sandord/Respawn.Postgres#5]
I tried to use PostgresCheckpoint and got this error

`
Npgsql.PostgresException : 42703: column p.consrc does not exist
Data:
  Severity: ERROR
  InvariantSeverity: ERROR
  SqlState: 42703
  MessageText: column p.consrc does not exist
  Hint: Perhaps you meant to reference the column "p.conkey" or the column "p.conbin".
  Position: 3309
  File: parse_relation.c
  Line: 3523
  Routine: errorMissingColumn
`

After googling I've found out the problem is PG12 removed the pg_constraint.consrc, this is tracked by PG12 removed the pg_constraint.consrc. 
Possible solution: downgrading to PG11 should work until a fix is released.

Well... What if I want to stay in PG12?

**Comment by sandord** [comment]
Hi, which version of Npgsql.Postgres are you on?

Since version 1.0.15 (per [this commit](https://github.com/sandord/Respawn.Postgres/commit/52fca1a00651eeba94503cf3b735478fc598f865)) the mentioned columns aren't hardcoded anymore so it sounds like you're on an older version.
